version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:management'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app-network
  cart:
    image: 'eliecookie/producer-consumer-rabbit-cart:latest'
    # build:
    #   context: .
    #   dockerfile: apps/cart/Dockerfile
    ports:
      - '3001:3001'
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - app-network

  orders:
    image: 'eliecookie/producer-consumer-rabbit-orders:latest'
    # build:
    #   context: .
    #   dockerfile: apps/orders/Dockerfile
    ports:
      - '3002:3002'
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
