# Use official Node.js image as a base
FROM node:16

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json (or yarn.lock)
COPY apps/cart/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY apps/cart .

# Expose the port the app runs on
EXPOSE 3001

# Start the app
CMD ["npm", "run", "start"]
